#!/bin/sh

# Repack pico libraries into a single altlinux RPM
# Debian packages are downloaded from
#   http://labs.picotech.com/debian/pool/main/
# check for new versions!


info='\
libp libpicoipp  1.4.0 4r133
libp libps4000   2.1.83 2r3073
libp libpicohrdl 2.0.17 1r1441
'
#arches="amd64 i386"
arches="amd64"
rpm_ver="1.2"
rpm_name="libpico"

for arch in $arches; do

  dest="libpico.debian"
  rm -rf -- ${dest}/usr

  libdir=/usr/lib
  [ "$arch" != "amd64" ] || libdir=/usr/lib64
  incdir=/usr/include/pico
  docdir=/usr/share/doc/pico
  mkdir -p -- $dest/$libdir $dest/$incdir $dest/$docdir

  echo "$info" |
  while read dir name ver rel; do
    [ -n "$name" ] || continue
    fname=${name}_${ver}-${rel}_${arch}.deb
    oname=${name}-${ver}.orig
    dname=${name}-${ver}

    echo Processing: ${name}_${ver}-${rel}_${arch}
    ### download packages.
    ### check for new versions!
    [ -f $fname ] ||
      wget http://labs.picotech.com/debian/pool/main/${dir}/${name}/${fname}

    rm -rf -- ${dname} ${oname}
    alien --to-deb -g ${fname}
    mv ${oname}/opt/picoscope/lib/*               ${dest}/$libdir
    mv ${oname}/opt/picoscope/include/*/*         ${dest}/$incdir
    mv ${oname}/opt/picoscope/share/doc/${name}/* ${dest}/$docdir
    mv ${oname}/usr/share/doc/${name}/*           ${dest}/$docdir
#    rm -rf -- ${dname}
  done
done

cd libpico.debian && ./build
