#!/bin/sh

# Repack pico libraries into a single altlinux RPM
# Debian packages are downloaded from
#   http://labs.picotech.com/debian/pool/main/
# check for new versions!


info='\
libp libpicoipp  1.3.0 4r21
libp libps4000   2.1.0 2r570
libp libpicohrdl 2.0.17 1r1441
'
#arches="amd64 i386"
arches="amd64"
rpm_ver="1.2"
rpm_name="libpico"

for arch in $arches; do

  dest="$HOME/tmp/libpico-buildroot"
  rm -rf -- ${dest}

  libdir=/usr/lib
  [ "$arch" -ne "amd64" ] || libdir=/usr/lib64
  incdir=/usr/include/pico
  docdir=/usr/share/doc/pico
  mkdir -p -- $dest/$libdir $dest/$incdir $dest/$docdir

  echo "$info" |
  while read dir name ver rel; do
    [ -n "$name" ] || continue
    fname=${name}_${ver}-${rel}_${arch}.deb
    dname=${name}-${ver}

    echo Processing: ${name}_${ver}-${rel}_${arch}
    ### download packages.
    ### check for new versions!
#     wget http://labs.picotech.com/debfix/pool/main/${dir}/${name}/${fname}

    rm -rf -- ${dname}
    alien --to-rpm -g ${fname}
    mv ${dname}/opt/picoscope/lib/*               ${dest}/$libdir
    mv ${dname}/opt/picoscope/include/*/*         ${dest}/$incdir
    mv ${dname}/opt/picoscope/share/doc/${name}/* ${dest}/$docdir
    mv ${dname}/usr/share/doc/${name}/*           ${dest}/$docdir
    rm -rf -- ${dname}
  done

  cat > ${rpm_name}.spec <<EOF
Name: ${rpm_name}
Version: ${rpm_ver}
Release: 0
License: non-free
Summary: PicoScope libraries
Group: Converted/libs
%description
Picoscope libraries

%files
%dir $incdir
%dir $docdir
$libdir/*
$incdir/*
$docdir/*
EOF

  rpmbuild -bb libpico.spec
  mv -f /home/sla/RPM/RPMS/x86_64/${rpm_name}-${rpm_ver}-0.x86_64.rpm ${rpm_name}-${rpm_ver}-0.$arch.rpm
#  rm -rf -- ${dest} libpico.spec
done
