#!/bin/sh

# same as record_gen but in interactive mode

../pico int <<EOF
log  --file=rec.log
chan --channel=A --coupling=DC --enable --range=0.4
chan --channel=B --disable
gen  --pk2pk=0.35 --cycles=5 --startf=1000 --trig_gen_src=soft
trig --disable
rec  --file=rec.dat --time=0.1 --rate=100000 --trig_gen
EOF

