#!/bin/sh -efu

name=pico_osc
ver=2.3
tag=
DIR="$name-$ver"

rm -rf -- "$DIR"
mkdir "$DIR"
cd "$DIR"

git clone ../../ .
[ ! -d modules ] || git submodule init
[ "$tag" = "" ]  || git checkout --detach $tag
[ ! -d modules ] || git submodule update

[ ! -d modules ] || rm -f modules.tar update_modules
rm -rf .git .gear

mkdir debian
for f in changelog control copyright rules conffiles; do
  [ ! -f "../$f" ] || sed 's/${ver}/'$ver'/g' ../$f > debian/$f
done

dpkg-buildpackage --build=any 2>&1 | tee build.log

cd ..
#rm -rf -- "$DIR"
